### ISSUE TITLE
Tracking issue: Full DreamCoder Comparison

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#50]
# big things
- [ ] expressivity comparison
- [ ] timing comparison
- [ ] memory comparison
- [ ] paper writing

# Theo things
- [ ] topK stuff
- [ ] add back in the single Task check. Search `no_opt_single_use` and add it in those 2 places, you can adapt the error messages and such from how the `no_opt_single_use` case looks. Your task data structure should still be around so this should be straightforward. Just giving you this to get used to the new codebase!
- [ ] 

# Matt things
- [ ] use conflicts, exact utility, and new rewriting
- [ ] try Alex's approach of assignment splitting on the spot
- [ ] try 
- [ ] add refinements
- [ ] comment the code
- [ ] add free var pruning as a partial + final pruning instead of just the negative check

# New short term todo list
- [ ] figure out how to get `frontiersOverTime` for the domains where we dont have it
- [x] improved `--fmt=dc` #89 
  - update `--fmt=dc` to read the `productions` and process them in reverse order to add them as `fn_i`s
  - then have it rewrite the list of programs with them in order of last to first function (this is backwards compatible with them already being rewritten)
  - then have it make sure there are no remaining `#` in the programs
- [x] understanding what DC is doing better
   - check out whether DC drops all but the best program or something before building vspaces? -> it does topK=2 so that means best 2 from each frontier
   - check out why it is that DC message says "used X times in the best program for each frontier" how do they rank best and are they skipping work by only doing the best program? -> this printout is done with topK=1
- [ ] write something to take `iterations_4.json` and produce an `iterations_3_expected_out.json` by just taking the DSL and frontiers from it. This will get us expected output files without ever having to run dreamcoder so we can look into stitch-equivalence right away! Oh wait note that the rewritten frontiers might not quite be the same, idk if itll be a superset or what - but another round of searched happened in between
- [ ] rerun a real single step of a DC experiment as a prelim test to make sure its output is the same as the predicted output. Same with the log probabilities for DSL elems make sure those line up. Later we will do this for all the ones we recreate.
- [ ] Set up total memory and total time checks - should we measure this externally or within? If within, do we need random checks inserted all the time?
- [ ] write a thing that takes a DC-format expected output and puts it in stitch format - with as much of the stitch output info as you can recreate. So basically name the invs, create the dc_string the rewritten etc. This will be useful for actually looking at what gets produced, checking it against stitch metrics like compressivity to understand why something was or wasnt found, etc.
- [ ] write a stitch flag for outputting in DC format but with logProbability set to NaN
- [ ] write a python thing that takes a stitch output file in DC format and adjusts the NaN to be the actual likelihood fit to the real data.
- [ ] does topK actually use a logprob ranking or are they all 0 anyways? Is it weird that my files are all zero or should they be ranked? does compression rank them before running?

# Other Todos

- [x] Extract DC data from the PLDI artifact @theoxo 
- [x] Preliminarily run stitch on the DC data
- [ ] Critical
  - [x] #36 
  - [ ] #60 
  - [x] #37 
- [ ] give compress.rs an identical format to compression.ml so it can drop-in replace (good to have in general and for this project!). Ask cathy if this API differs from the LAPS compression API and if so we should just do both APIs.
- [ ] Write the python code to get us exact DC-assigned scores of top K inventions that stitch returns, so we can grab the very best invention as ranked by DC and compare it to what DC itself returns
- [x] Look into #40 more as it would help a lot with paper story
- [x] Consider a stronger upper bound on the holes based on some multiuse analysis or even some very very weak bounding on the multiuse. 
- [ ] start writing!

@mlb2251  Active threads:
- [x] https://github.com/mlb2251/stitch/issues/79
- [ ] https://github.com/mlb2251/stitch/issues/60
- [ ] https://github.com/mlb2251/stitch/pull/83
- [x] https://github.com/mlb2251/stitch/issues/37
  - [x] https://github.com/mlb2251/stitch/pull/86

@theoxo: I put together a list of things you could help out with since you were looking for ways to help!
- [x] Get DreamCoder compression running on Sketch4, and make note of how you did it because I'll need it on my account too! Get it running on this file https://github.com/mlb2251/stitch/blob/main/data/dc/dc_logo_log.json and write up how to run it. I think we can keep any experiment scripts / instructions in the repo
- [x] when we get the dreamcoder pldi artifact data, get all our data formatted right so we can run these benchmarks
- [x] Tons of things below that you can take a stab at if you want in the mean time. These are all things that I would eventually do but would be really useful to have help with and will get you into the codebase. Feel free to ask questions of course when doing any of it! Submit everything as a PR so I can check it over as you get used to the codebase!
    - [x] [have it mkdir "out/" · Issue #38 · mlb2251/stitch · GitHub](https://github.com/mlb2251/stitch/issues/38) this is trivial
    - [x] [throw out inventions with negative utilty · Issue #35 · mlb2251/stitch · GitHub](https://github.com/mlb2251/stitch/issues/35) you'd want to do this right after calculating utility. Search `let utility = ` to find 3 places you'll want to add this and `let upper_bound =` for 2 more places to add it.
    - [x] [DC compat: remove inventions only used by a single Task · Issue #51 · mlb2251/stitch · GitHub](https://github.com/mlb2251/stitch/issues/51) This pruning should go  in all the same places as the pruning that checks for things that apply only at single nodes. You can find that by searching `no_opt_single_use` and doing this right after that in those 5ish places.
    - [x] [More flexible json format spec with `--fmt` enum · Issue #43 · mlb2251/stitch · GitHub](https://github.com/mlb2251/stitch/issues/43) This will just take some reading up on the `clap` library to figure out how to make a cmdline arg that takes multiple options. Either an enum if they have a nice way to do that (I think they do) or worst case just make it a string.
    - [x] [Add single_use and single_task checks to arity 0 too! · Issue #64 · mlb2251/stitch · GitHub](https://github.com/mlb2251/stitch/issues/64) search "arity 0 inventions" to find the place where we construct the arity 0 inventions. Add single-use pruning (search "no_opt_single_use" to see what that looks like) as well as single-task pruning (which you added in issue 51)
Thanks so much for the help!!! :)) 🎉 ❤️

**Comment by mlb2251** [comment]
retiring this old todo list
